name: Deploy Firebase Apps

on:
  push:
    branches:
      - main

jobs:
  deploy-board:
    name: Deploy Board Screen (Web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Board App (Flutter Web)
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: |
          cd display_screen_panel
          flutter pub get
          flutter build web

      - name: Deploy Board Hosting
        run: |
          cd board_app
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-admin:
    name: Deploy Admin App (Web)
    runs-on: ubuntu-latest
    needs: deploy-board

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
         channel: stable

      - name: Build Admin APK
        run: |
          cd manage_app/rank_manage
          flutter pub get
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rank-admin-apk

          path: manage_app/rank_manage/build/app/outputs/flutter-apk/app-release.apk

